version: '3.3'

services:
  
  web:
    build: .
    env_file: .env
    volumes:
      - ./shop_project:/code/
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: [ "sh", "-c", "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8001" ]

  db:
    env_file: .env
    image: postgres:12.3-alpine
